### ISSUE TITLE
Playing with Structs

### ISSUE THREAD

**Issue by nicoolas25** [benoittgt/PhubMe#12]
The code often manipulate (no that) long tuples, for instance:
- in the [comment_parser.ex](https://github.com/benoittgt/PhubMe/blob/master/lib/phubme/comment_parser.ex#L11) and
- in the [nickname_matcher.ex](https://github.com/benoittgt/PhubMe/blob/master/lib/phubme/nicknames_matcher.ex#L6).

These tuple represent a comment. The comments are built by the parser, then they are filled or discarded by the nickname matcher, and finally they are used to send the notification on Slack. This flow is very clear in those lines:

``` elixir
PhubMe.CommentParser.process_comment(conn.body_params)
  |> PhubMe.NicknamesMatcher.match_nicknames
  |> PhubMe.Slack.send_private_message
```

The structure of the data that is flowing into this pipeline is somehow implicit. It is a tuple where the position of each element is _known_.

An idea, which is also an excuse to play a bit more with Elixir, would be to introduce an [elixir structure](http://elixir-lang.org/getting-started/structs.html) to represent all the data relative to a message. And instead of using different tuples, keep using the same structure in the pipeline.

It will probably introduce a bit of overhead in the code but I hope it will make it more explicit and clear.

What do you think of this refactoring?

**Comment by nicoolas25** [comment]
Here is one interesting read related to this: https://engineering.appcues.com/2016/02/02/too-many-dicts.html

**Comment by benoittgt** [comment]
Thanks will have a look at it

**Comment by benoittgt** [comment]
Done with https://github.com/benoittgt/PhubMe/pull/13
